### ISSUE TITLE
add more optional disk  parameters  when creating new Disks 

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#133]
// Clone makes sure that the disks are cloned from the template and are not linked.
	// Defaults to false.
	// +optional
	Clone *bool `json:"clone,omitempty"`

	// Sparse indicates that sparse provisioning should not be used and disks should be preallocated.
	// Defaults to false.
	// +optional
	Sparse *bool `json:"sparse,omitempty"`

	// Format is the disk format that the disks are in. Can be "cow" or "raw". "raw" disables several features that
	// may be needed, such as incremental backups. Defaults to "cow".
	// +optional
	Format string `json:"format,omitempty"`

**Comment by janosdebugs** [comment]
Fixed in #127 and #131
