### ISSUE TITLE
when creating a new VM from template specify optional disk type

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#134]
// Clone makes sure that the disks are cloned from the template and are not linked.
// Defaults to false.
// +optional
Clone *bool `json:"clone,omitempty"`

// Sparse indicates that sparse provisioning should not be used and disks should be preallocated.
// Defaults to false.
// +optional
Sparse *bool `json:"sparse,omitempty"`

// Format is the disk format that the disks are in. Can be "cow" or "raw". "raw" disables several features that
// may be needed, such as incremental backups. Defaults to "cow".
// +optional
Format string `json:"format,omitempty"`

**Comment by janosdebugs** [comment]
Implemented in  #131 and #127
