### ISSUE TITLE
when creating a new VM from template specify its bootable disk size

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#136]
when we want to have an initially larger disk size, it might be useful to have such an optional param during VM Creation.

**Comment by janosdebugs** [comment]
I don't think we should add this to go-ovirt-client purely because it's a separate API call after the VM has been created, we can't pass it along with the VM creation. If we add "extra stuff" to the VM creation it will become hopelessly bloated like the TF provider code currently is.
