### ISSUE TITLE
introduce ISO disks support - add ContentType  Param when creating disk

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#139]
ContentType param is a string that can contain:
"data" - default
"iso"
"hosted_engine"
"hosted_engine_sanlock"
"hosted_engine_metadata"
"hosted_engine_configuration"
see https://ovirt.github.io/python-ovirt-engine-sdk4/master/types.m.html#DiskContentType

**Comment by janosdebugs** [comment]
Hey @eslutsky why do we need ISO support?

**Comment by eslutsky** [comment]
it's a nice feature and will benefit our tests, and a relatively easy change,  we can add it later .

**Comment by janosdebugs** [comment]
This is a considerable amount of work, we won't do it unless we actually need it. It's a huge overhead for a few tests.
