### ISSUE TITLE
check if its possible to implement GetAffinityGroupByName  

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#149]
the current lookup implementation is not very straightforward:
https://github.com/openshift/cluster-api-provider-ovirt/blob/3643d913dcfd76ad84987e6295672b46bbf8dcac/pkg/clients/ovirt/impl.go#L422-L440

**Comment by janosdebugs** [comment]
There is no API call to fetch affinity groups by name, we can only port that logic. Would you rather have an API call to get an affinity group by name, or an API call to verify a list of affinity groups?
