### ISSUE TITLE
new.go Transport misses proxy

### ISSUE THREAD

**Issue by evelynmitchell** [oVirt/go-ovirt-client#183]
## Describe the bug

At lines 138 to 141, where the http Client is set up, the Proxy is not mentioned.

This should include

Proxy: http.ProxyFromEnvironment

In order to correctly pick up the Proxy from the environment.

## To Reproduce

Set up a proxy in the test environment that is required for any network traffic to pass externally, such as an OAuth proxy.

Without this line, the connection to the larger network should fail.

With this line, the connection should succeed, after connecting to the proxy.

## Expected behavior
 
When a proxy is definined in the environment, it is used.

**Comment by janosdebugs** [comment]
Hello @evelynmitchell thank you very much for the issue and the PR, most of the team is out this week and we will get back to this issue early next week.
