### ISSUE TITLE
Mock for IP address assignment doesn't work

### ISSUE THREAD

**Issue by Darth-Mera** [oVirt/go-ovirt-client#215]
## Describe the bug

When using WaitForNonLocalIP after VM start the IP never gets assigned

## To Reproduce

Please see: https://github.com/oVirt/terraform-provider-ovirt/pull/435

**Comment by janosdebugs** [comment]
After debugging this issue, it seems that the test code in oVirt/terraform-provider-ovirt#435 does not have an ovirt_nic resource that would attach a network interface to the VM, which results in the simulation not adding an IP address.

However, the resulting error messages are hard to debug, so I will add a PR that explicitly checks for the presence of a NIC and warns if the VM has no NIC attached.
