### ISSUE TITLE
upload  image examples missing RetryStrategy 

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#33]
for example https://github.com/oVirt/go-ovirt-client/blob/b35ac413da4dcab9020bd66b1f4c28e41f8a938f/example_vm_uploadimage_test.go#L38

it's missing the RetryStrategy.

**Comment by janosdebugs** [comment]
@eslutsky the retry strategies are a set of optional parameters, typically you wouldn't mess with those unless you have a VERY specific reason, that's why the examples don't have them.
