### ISSUE TITLE
add to test + mock ability to handle multiple SDs 

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#54]
multiple storage domains are needed for copying disks between SDs tests.
currently there is setupTestStorageDomainID which returns one SD only.

https://github.com/oVirt/go-ovirt-client/blob/7326702e5015c5fd6008d1b2153c20a6c03174f5/test_helper.go#L168

**Comment by janosdebugs** [comment]
I will try to add these, but we may have to add a condition to the tests in case no second storage domain is available.
