### ISSUE TITLE
Image download commands

### ISSUE THREAD

**Issue by pkliczewski** [oVirt/go-ovirt-client#7]
I would like to use the client as a replacement for ovirt sdk in CDI. Here you can find list of commands [here](https://github.com/kubevirt/containerized-data-importer/blob/fceae7e12e91a5d01ff6f4d779cd9a39462d137b/pkg/importer/imageio-datasource.go#L366).

Currently we use the sdk to import disks from RHV to CNV and we had to implement bunch of interfaces to be able to mock the calls during tests. This client would help us to delete good amount of code without changing functionality.

**Comment by janosdebugs** [comment]
Hey @pkliczewski thank you very much for your work on creating those interfaces, these will definitely come in handy when developing this library. We'll add your API calls and appropriate mocks for it using yours as a template. I'll keep you posted.

**Comment by janosdebugs** [comment]
@pkliczewski this is now merged and tagged as v0.5.0, feel free to use. Let us know if you run into any issues.
