### ISSUE TITLE
add test to image uploads to use different disk allocation policy (thin or preallocated)

### ISSUE THREAD

**Issue by eslutsky** [oVirt/go-ovirt-client#80]
we need to add a test to upload_image to use different preallocation policies than the original image has :
https://github.com/oVirt/go-ovirt-client/blob/main/client_disk_uploadimage_test.go

**Comment by eslutsky** [comment]
we can see example  dealing with various image types uploads here https://github.com/oVirt/ovirt-imageio/blob/master/test/client_test.py

**Comment by janosdebugs** [comment]
@eslutsky we support the sparse flag already. What's missing here?

**Comment by janosdebugs** [comment]
I believe this is fixed in #131
